### ISSUE TITLE
Implement Ollama

### ISSUE THREAD

**Issue by jimccadm** [Leon-Sander/local_multimodal_ai_chat#1]
Great, really great project! Can I suggest you consider Ollama to allow for alternative models to be tested out? Also for folks less familiar with downloading models from HF etc.

**Comment by Leon-Sander** [comment]
I like the idea. I haven't worked much with Ollama yet, I would have to look into it at first.
Do you have a specific Idea how to integrate it? 
I saw there is a Ollama langchain integration as well, this could also be a possibility.

Feel free to experiment with integrating Ollama and open up a pull request if you have a suitable solution.
I am going to look into it as well in the meantime.

**Comment by Leon-Sander** [comment]
See commit [877c159](https://github.com/Leon-Sander/local_multimodal_ai_chat/commit/877c159143f465a16c405e18bee7315ac14a54a3)
