### ISSUE TITLE
no such table: messages

### ISSUE THREAD

**Issue by JTMarsh556** [Leon-Sander/local_multimodal_ai_chat#13]
I was following along with the video but I started to have issues with the chat history section and specifically with json.  I decided to just copy the files and try to run it as I will admit I am new to all of this.  

Anyhow, when I run it get the error below.

  File "C:\xxxxx\database_operations.py", line 96, in get_all_chat_history_ids
    cursor.execute(query)
sqlite3.OperationalError: no such table: messages

**Comment by Leon-Sander** [comment]
The code in the main branch is quite changed compared to the video code. 
The video code can be looked in the specified branch https://github.com/Leon-Sander/local_multimodal_ai_chat/tree/YTVideoCodeVersion

Your error occurs if step 7 from the Getting Started section in the readme file was not done:
```python database_operations.py``` This will initialize the sqlite database for the chat sessions.

**Comment by JTMarsh556** [comment]
I see.  That works.  Sorry, I missed that when I cut over from the youtube video to main branch.
