### ISSUE TITLE
Pdf chat  issue

### ISSUE THREAD

**Issue by Chiru137** [Leon-Sander/local_multimodal_ai_chat#18]
I was using your main failed and done the steps as given.But while inputing the question it gives error.It doesnt give any answer.
![Screenshot 2024-03-27 113738](https://github.com/Leon-Sander/local_multimodal_ai_chat/assets/164709609/55dc9a55-060f-4d55-a63f-e15d2152bfdc)

**Comment by Chiru137** [comment]
The ui is correct but while asking question it gives error

**Comment by Leon-Sander** [comment]
You cloned the main branch and followed all the steps in get started?
Can you provide a screenshot without the error, after starting the UI?
Also please send the full error message from the terminal.
