### ISSUE TITLE
load INSTRUCTOR_Transformer max_seq_length  512

### ISSUE THREAD

**Issue by sanelez** [Leon-Sander/local_multimodal_ai_chat#19]
Error when loading PDF....( drag and drop or through browse for file.
"load INSTRUCTOR_Transformer
max_seq_length  512........"

**Comment by Leon-Sander** [comment]
This text should be there, is there an actual error message, or what is your problem?

**Comment by CHYoon8** [comment]
I got the same issue. 
when I used sentence-transformers==2.3.1 , which is in your requirements.txt, it caused Error:
"TypeError: INSTRUCTOR._load_sbert_model() got an unexpected keyword argument 'token'"

I have tried sentence-transformers==2.2.2, and got :
![image](https://github.com/Leon-Sander/local_multimodal_ai_chat/assets/122321126/fc7bcaae-c345-4a6d-80e4-3c40b541063d)

**Comment by Leon-Sander** [comment]
Could you elaborate on what the actual bug was? Did it just not index the pdf files or did you get an error message?
This might help someone else.

**Comment by joaquindev23** [comment]
> Tenía un insecto de croma-hnswlib que depende del cromatodb, hice una rebaja de la degradación del paquete de cromadb a 0.4.2 e hizo el truco.

Explain it better please

**Comment by B7-9414** [comment]
Yes, there is a few bugs with pdf feature : 
1. reinstall sentence-transformers (pip install sentence-transformers==2.2.2 )
2. you should downgrade Chromadb to 0.4.3 (pip install chromadb==0.4.3)
3. there is a code bugs not sure how to fix it:
       - when you upload a pdf file => will proses it looks ok
       - once you sending your questions/prompts and click enter the pdf have uploading will be disappear => means you can 
       chat with the pdf, also the pdf toggle set to true after you click to send button.

if anyone fix the code bugs ping me :)) ty

**Comment by joaquindev23** [comment]
![Captura desde 2024-04-18 19-38-44](https://github.com/Leon-Sander/local_multimodal_ai_chat/assets/120047856/d00f3532-1a10-47e1-b755-835294088df6)
![Captura desde 2024-04-18 19-41-08](https://github.com/Leon-Sander/local_multimodal_ai_chat/assets/120047856/f8379675-bf3e-4aa0-a6cf-c38c4e11a6eb)

**Comment by joaquindev23** [comment]
![Uploading Captura desde 2024-04-18 19-41-08.png…]()

**Comment by Leon-Sander** [comment]
@B7-9414 
>     3. there is a code bugs not sure how to fix it: @Leon-Sander
>        - when you upload a pdf file => will proses it looks ok
>        - once you sending your questions/prompts and click enter the pdf that you have uploading will be disappear =>
>        means you can NOT chat with the pdf, also the pdf toggle above set to true after you click to send button.
>        if anyone fix the code bugs ping me :))

This is intended and no bug. After uploading the pdf, it gets ingested into the vectordb, there is zero reason for the pdf to still be there. If it would still be there, then it would trigger the upload function again and again, populating your vectordb with the same document over and over.
So all pdfs you uploaded over time are inside the vectordb, you can chat with them at any time.

**Comment by Leon-Sander** [comment]
Solution to @joaquindev23 in #23

**Comment by B7-9414** [comment]
@Leon-Sander 
I have tested that out won’t ingested into the vectordb when you upload the pdf file. you can just upload/drop it manually to pdfs folder then toggle it on/True.

also, if you toggle this off still you can chat with the pd  Even though,  when hit clear caches and refresh the page. we should clear the it from streamlit UI setting.

**Comment by Leon-Sander** [comment]
@B7-9414 
In my case it gets ingested into the vectordb, thats how I designed the code. Also dropping the pdf in the folder does nothing since I didn't program it to read the pdf folder while running.

**Comment by B7-9414** [comment]
@Leon-Sander 
As you see when you I upload a pdf file has some content about Bassam's info. the toggle will set to on/True and the bassam pdf file I have upload will disappear once I send the question. mean while i have healthcare pdf file under pdfs folder as shown.

when ask/send a questions about Bassam pdf which I have upload won't gave an answer cuz, is NOT in the vector db. 
when I ask questions about healthcare related it to the pdf which I have locally under pdfs folder. will return the valid answer which means its stored in vector db.

![1](https://github.com/Leon-Sander/local_multimodal_ai_chat/assets/40012781/17ceeb07-23ef-457a-8f5c-818f99e5485b)
![1](https://github.com/Leon-Sander/local_multimodal_ai_chat/assets/40012781/77ae8797-e217-44b5-b904-1086ccf922b3)

**Comment by Leon-Sander** [comment]
It seems that you made some changes to the code, maybe that's the reason.

Without seeing your code version or a video demonstration, I can't comprehend you problem since at my end it works exactly as intended.

**Comment by B7-9414** [comment]
@Leon-Sander  
I have re clone the main branch without changed anything. still the same issue :(( I have tried to fix that could not !! plz test that from your end! ty

**Comment by Leon-Sander** [comment]
@B7-9414 Just cloned the repo and tested it again, here the command line output when I drag in a pdf in the streamlit frontend, as you can see, the adding worked. The pdf contained my resume, so information which the model could not know beforehand.
Then I asked a question, and the pdf chain got loaded and answered my question with contents from the pdf.
Works like a charm, no problems.

![image](https://github.com/Leon-Sander/local_multimodal_ai_chat/assets/72946124/0af0ed64-b470-4fdf-acd1-87d4f0f0a7dc)

**Comment by B7-9414** [comment]
@Leon-Sander 
yes, I have the something but, when you ask questions about the pdf you have uploaded it won't get a valid answer. we may need to to have another chain to handle that , rather than one.

then, try to add it locally under pdfs folder and toggle it on u will get a valid answer .

**Comment by Leon-Sander** [comment]
@B7-9414 The problem might be the way your pdf files are structured. I provided the hover pdf in this repository, please add it in the frontend and then ask "what is the HoVer dataset about?". If you get an answer, it worked, and your problem probably lies in your pdf files.

**Comment by Kanav31** [comment]
![image](https://github.com/Leon-Sander/local_multimodal_ai_chat/assets/90086445/a008b365-9798-4754-af30-269e205a3237)
it gives me this error while returning answer to my chat?

**Comment by Kanav31** [comment]
![image](https://github.com/Leon-Sander/local_multimodal_ai_chat/assets/90086445/b34ab6c4-e47d-44e9-89d2-3d12ac0fe4ef)

although these run fine like I am getting all the print

**Comment by JTMarsh556** [comment]
> @B7-9414
> 
> > ```
> > 3. there is a code bugs not sure how to fix it: @Leon-Sander
> >    - when you upload a pdf file => will proses it looks ok
> >    - once you sending your questions/prompts and click enter the pdf that you have uploading will be disappear =>
> >    means you can NOT chat with the pdf, also the pdf toggle above set to true after you click to send button.
> >    if anyone fix the code bugs ping me :))
> > ```
> 
> This is intended and no bug. After uploading the pdf, it gets ingested into the vectordb, there is zero reason for the pdf to still be there. If it would still be there, then it would trigger the upload function again and again, populating your vectordb with the same document over and over. And obviously, since you just uploaded a pdf, you would want to chat with it, therefore the pdf toggle is set to true. So all pdfs you uploaded over time are inside the vectordb, you can chat with them at any time if the pdf toggle is true. If the pdf toggle is false, you chat with the model without pdf access.

Hi Leon, I am still learning so forgive me if this is a silly question but is the vectordb stored in the vram or is it stored on the drive and loaded based on the context of the question?  I assume the former but I can see the VRAM getting maxed out if the ingested data is a library vs a smaller set of files and was hoping there was a way to implement the latter.  

What are your thoughts on mass ingested file storage?

**Comment by Leon-Sander** [comment]
@JTMarsh556 vectordb is stored on the drive, and document search is performed in RAM. If you have enough RAM you can have a vectordb with a large amount of text ingested.

VRAM is used if the models are loaded on GPU.

**Comment by JTMarsh556** [comment]
Thank you.  That clarified things for me.  I appreciate you taking the time to explain that to me.
