### ISSUE TITLE
windows 11 users 

### ISSUE THREAD

**Issue by B7-9414** [Leon-Sander/local_multimodal_ai_chat#20]
I am facing this issue in win11 when I try to run pip install  requirement file anyone able to solve it ? 
![1](https://github.com/Leon-Sander/local_multimodal_ai_chat/assets/40012781/c27e3b34-90d0-48d3-bf94-ab5b97fa663d)

**Comment by Leon-Sander** [comment]
Try to install Microsoft C++ Build Tools as suggested within the error message.
![image](https://github.com/Leon-Sander/local_multimodal_ai_chat/assets/72946124/718a3816-a7d1-4143-a218-2b8c79af7574)

**Comment by B7-9414** [comment]
the issues has been fixed !
all you need to solve it. download https://visualstudio.microsoft.com/downloads/ then install all most all packages in there. this is the best solutions.
