### ISSUE TITLE
OperationalError: no such table: messages

### ISSUE THREAD

**Issue by joaquindev23** [Leon-Sander/local_multimodal_ai_chat#21]
**When installing all the requirements of the .txt file and doing the RUN I get this error. How would you add the table in this sense? Thank you**

![Captura desde 2024-04-01 23-52-44](https://github.com/Leon-Sander/local_multimodal_ai_chat/assets/120047856/5693e58f-43aa-4302-bc76-6ad097aa2e72)

**Comment by joaquindev23** [comment]
![Captura desde 2024-04-02 00-48-36](https://github.com/Leon-Sander/local_multimodal_ai_chat/assets/120047856/00633dbc-e0bf-45b5-b5ec-55977c5adcba)

**Comment by joaquindev23** [comment]
I was able to solve it by activating the sqlite3 database with the commands:

--> python3 database_operations.py

Tenk

**Comment by Leon-Sander** [comment]
> When installing all the requirements of the .txt file and doing the RUN I get this error. How would you add the table in this sense? Thank you

Point 7 i from the getting started section:
![image](https://github.com/Leon-Sander/local_multimodal_ai_chat/assets/72946124/b3982abb-b283-41aa-9886-3d72d9443cb7)

**Comment by joaquindev23** [comment]
After doing so I get this error, I cannot interact

![1](https://github.com/Leon-Sander/local_multimodal_ai_chat/assets/120047856/92351960-162d-4d28-b2de-db07fec2f1cd)
![2](https://github.com/Leon-Sander/local_multimodal_ai_chat/assets/120047856/e092a12b-a361-4266-af8c-d72631988ae7)

**Comment by gauravgary01** [comment]
I'm getting this error: No module named 'langchain'
![Screenshot 2024-04-04 010741](https://github.com/Leon-Sander/local_multimodal_ai_chat/assets/26687486/56522068-61f3-4830-a701-a522116f40b2)

**Comment by gauravgary01** [comment]
I am running on python 3.12.0 with pip_freeze.txt and requirements installed.

**Comment by B7-9414** [comment]
@joaquindev23 You should read the README and install all model from hugging face

**Comment by joaquindev23** [comment]
@B7-9414 Could you help me install the huggin face model? as I do

**Comment by Leon-Sander** [comment]
Solution in #23
