### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 512.00 MiB. GPU 0 has a total capacity of 1.96 GiB of which 225.06 MiB is free.

### ISSUE THREAD

**Issue by joaquindev23** [Leon-Sander/local_multimodal_ai_chat#24]
How can I solve this error?

![Captura desde 2024-04-18 20-52-49](https://github.com/Leon-Sander/local_multimodal_ai_chat/assets/120047856/ce0eb2ec-6f27-47bc-8a50-beeb958a6f45)

**Comment by Leon-Sander** [comment]
Either by using a GPU with more memory, since the message tells you that your GPU does not have enough memory. Or set gpu_layers to 0 in the config file, then the models will run on CPU.

**Comment by Leon-Sander** [comment]
As I already wrote, the config.yaml file, and if you didn't change it then line 11
