### ISSUE TITLE
Updating the repository to the newest version.

### ISSUE THREAD

**Issue by SJ-1407** [Leon-Sander/local_multimodal_ai_chat#27]
Following the tutorial, I have implemented the code along with additional features. However, I am encountering difficulties understanding the changes made in the project's main branch with respect to the tutorial.

While I would prefer not to clone the repository due to my existing code modifications, I am eager to integrate the improvements from the main branch, while understanding them as well.

Could you please suggest a suitable approach to achieve this integration without losing my local changes?

**Comment by Leon-Sander** [comment]
Thats really nice to hear, congrats on following along.

You could look at the changelog and maybe try to follow the changes made there.
Generally I would recommend:
First to change to st.chat_message from st.write.
Then implementing a sqlite Database to Save the Chat History.
Then adding Images and Audio to Chat History Saving and Loading.
Finally Model Caching.

You can look into the current code and try to understand the how these change integrate,
and then integrate into your code.

**Comment by SJ-1407** [comment]
<img width="374" alt="Screenshot 2024-05-26 121919" src="https://github.com/Leon-Sander/local_multimodal_ai_chat/assets/121049780/95afd1e9-81c0-4920-98c2-8ecc5bc9c0f0">

I tried to integrate sqlite database , but  I am getting chat history in reversed order.
Also , would like to know the location at which this database would  be created , so that I can view it using db browser.

**Comment by SJ-1407** [comment]
I wish to implement image generation as well as authentication mechanism.
It would be really great , if you could provide some steps  ore resources to do so.
Also , for authentication would it be nice to use streamlit only or switch to flask or fastapi?

**Comment by SJ-1407** [comment]
I also tried to implement A fucntionality of url chat , similar to pdf chat , where user provides the url and can chat with it , the problem I am facing is , although the scrapped text is getting added to the database , the answer is not being generated using the url's conntent.

import bs4
from langchain import hub
from langchain_chroma import Chroma
from langchain_community.document_loaders import WebBaseLoader
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from langchain.text_splitter import RecursiveCharacterTextSplitter
from chains import get_database,create_embedding

def load_url(url):
    loader = WebBaseLoader(
    web_paths=(url,),
    bs_kwargs=dict(
        parse_only=bs4.SoupStrainer(
        )
    ),
   )
    return loader
     
def get_data(loader):
    docs = loader.load()

    text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
    splits = text_splitter.split_documents(docs)

    return splits

def get_url_data(url):
    print("Loading url...")
    loader = load_url(url)
    splits=get_data(loader)
    print(splits)
    vector_db = get_database(create_embedding())
    vector_db.add_documents(splits)
    print("Documents added to db.")
