### ISSUE TITLE
Getting error while loading PDF

### ISSUE THREAD

**Issue by rs-biz** [Leon-Sander/local_multimodal_ai_chat#5]
I am getting this error . Any idea what might be the issue ?
llm_chains.py", line 43, in load_vectordb
    persistent_client = chromadb.PersistentClient(chromadb)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'chromadb' has no attribute 'PersistentClient'

**Comment by Leon-Sander** [comment]
You need to write a string into the PersistentClient, which will be the name of your vector database folder.
The error message seems to be something else, but try this out at first please.

``` persistent_client = chromadb.PersistentClient("chroma_db") ```

**Comment by rs-biz** [comment]
> You need to write a string into the PersistentClient, which will be the name of your vector database folder. The error message seems to be something else, but try this out at first please. If this does not solve the problem, then please post the complete error message.
> 
> `persistent_client = chromadb.PersistentClient("chroma_db")`

Thank you so much for responding ! I am getting the following error message after making the change you recommended . Confirmed that I have a folder chroma_db in the same directory as the app.py. I am running python 3.12 version.

AttributeError: module 'chromadb' has no attribute 'PersistentClient'
Traceback:
File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
File "/app.py", line 134, in <module>
    main()
File "/app.py", line 87, in main
    add_documents_to_db(uploaded_pdf)
File "/Users/ramesh/Bizagi/code/Bchat/pdf_handler.py", line 27, in add_documents_to_db
    vector_db = load_vectordb(create_embeddings())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/llm_chains.py", line 45, in load_vectordb
    persistent_client = chromadb.PersistentClient("chroma_db")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Leon-Sander** [comment]
Which requirements file did you install, and did you upgrade pip to the newest version before installing the requirements?

**Comment by rs-biz** [comment]
Thanks again for responding . Yes, I did upgrade pip before installing. I used requirements.txt that is in the repo as requirement file . Confirming that folder chroma_db exist in same folder as app.py.

**Comment by Leon-Sander** [comment]
I cannot reproduce the error, I installed the repository based on the steps in the readme file, and it worked.

After some research I found a suggestion to try: ```pip install --upgrade chromadb```

If this does not work, please post the output of: ```pip list```
And the whole content of the llm_chains.py file.
