### ISSUE TITLE
Json files are saved in different format in Windows 

### ISSUE THREAD

**Issue by DEVdv2006** [Leon-Sander/local_multimodal_ai_chat#7]
I am working in windows and here chat session json files are saved in different format,here there is minor difference where element dictionaries don't have key "type" and values "human" or "ai"

Example 
[
{content:"hi", additional kwargs:{}, example:False},
{content:"hello I am ai Chatbot ", additional kwargs:{}, example: False},
]

load_chat_history_json() function in utils.py will be affected by this

**Comment by Leon-Sander** [comment]
I just updated the code to a new version, which saves the chat history into a SQLite database. With that, this problem is circumvented.
