### ISSUE TITLE
Type error occurred while handling pdf 

### ISSUE THREAD

**Issue by DEVdv2006** [Leon-Sander/local_multimodal_ai_chat#8]
I am working on windows,where I encountered this type error it states that INSTRUCTOR._load_sbert_model() got an unexpected argument 'token', I guess this error occurred due to version issues of sentences -transformers , currently I am using sentence -transformers version 2.3.1, previously I was using version 2.2.2 where it causes an import error that states that dependencies of InstructorEmbedding not found, I guess the root issue is related to sentence -transformers versions 
![IMG_20240201_192029](https://github.com/Leon-Sander/local_multimodal_ai_chat/assets/129303395/e2d1cf81-0477-48da-bf21-5032c6485513)

**Comment by lauraramoningelan** [comment]
I had the same problem and it worked for me to do "pip uninstall sentence-transformers" and then reinstall the library with "pip install sentence-transformers==2.2.2".

**Comment by Leon-Sander** [comment]
@krshubhamm do you have Microsoft Visual C++ 14.0 or greater installed as mentioned in the error message?

**Comment by krshubhamm** [comment]
no do i have to install c++??

**Comment by Leon-Sander** [comment]
Yes it seems that you have to install it. "hnsw", the underlying implementetion of many vector databases seems to work with C++, which makes sense for speed purposes. 
I would suggest that you follow the link mentioned in the error message and install the newest Microsoft Visual C++ version.

**Comment by DEVdv2006** [comment]
> ![image](https://private-user-images.githubusercontent.com/154420581/304319205-348e9598-193e-4e0a-832c-c63cb30ac211.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MjEwNDYsIm5iZiI6MTcwNzgyMDc0NiwicGF0aCI6Ii8xNTQ0MjA1ODEvMzA0MzE5MjA1LTM0OGU5NTk4LTE5M2UtNGUwYS04MzJjLWM2M2NiMzBhYzIxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxMDM5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTQzMjE2ODEwMjEyOGY1NzUxODhhMDBkZTA0MDJkZDI5ODZhNjljYTc2ZmJhZDZhYzhkNDEzOTIwM2VjMmE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yhoHPfXlP4sLsmICjNUUr1FGxhY_WSZOq2ut6ZFRnfg)
> 
> Can you please help me to solve this issue as i had already installed chromadb

Go to the link given in error and download it ,I think it will solve the problem

**Comment by krshubhamm** [comment]
![Screenshot (12)](https://github.com/Leon-Sander/local_multimodal_ai_chat/assets/154420581/d5f2e4a1-0758-4247-82ce-c0396dce82c4)

How should i resolve this .I think there is some issue in my chat history

**Comment by Leon-Sander** [comment]
@krshubhamm In the config file just add "/" to the chat sessions path, so it looks like this:
```chat_history_path: "./chat_sessions/"```

I would recommend downloading the newest version of the code, which saves and loads the chat sessions in a database.
You need to run ```python database_operations.py``` first to create the database.

**Comment by lauraramoningelan** [comment]
> ![Screenshot (12)](https://private-user-images.githubusercontent.com/154420581/304637318-d5f2e4a1-0758-4247-82ce-c0396dce82c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4OTk5MjksIm5iZiI6MTcwNzg5OTYyOSwicGF0aCI6Ii8xNTQ0MjA1ODEvMzA0NjM3MzE4LWQ1ZjJlNGExLTA3NTgtNDI0Ny04MmNlLWMwMzk2ZGNlODJjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQwODMzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNGI5YzhmMTY2YjAyMjZhMjcwOTg2MWZlZTJhZDc3MzAzODhiYTMxODk1NTM0MmE4MTg4MzUxZmI0OWEyMGYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9us9AWSt2-Q3Bi0Quj37fmANdOZKd5DYt5TFWS4Q8QA)
> 
> How should i resolve this .I think there is some issue in my chat history

**Have you tried changing the time format? Instead of : , change it to _ or - ?**

**Comment by Shmoji** [comment]
> I had the same problem and it worked for me to do "pip uninstall sentence-transformers" and then reinstall the library with "pip install sentence-transformers==2.2.2".

I also had the original problem and this solved it. Now i have the issue that only CPU is being used and not GPU - but that's a different issue

**Comment by JTMarsh556** [comment]
> ###
> ** [lauraramoningelan](/lauraramoningelan)**

This worked for me.
